name: System Updates to Slack Channel

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string


jobs:
  slackNotification:
    name: System Updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: '#ff00ff'
          SLACK_ICON: https://uploads-ssl.webflow.com/63446087cd546e4cef3653d8/634e9b5e944ad888f8aebd3f_bw-logo.svg
          SLACK_MESSAGE: '${{ environment }} - ${{ branch }}'
          SLACK_TITLE: 'Success Deploying to ${{ environment }}'
          SLACK_USERNAME: deployment-bot
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          MSG_MINIMAL: true

